apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
    a3ViZUNBMB4XDTIyMDEzMDExNDM0MVoXDTMyMDEyOTExNDM0MVowFTETMBEGA1UE
    AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOw9
    jbit4T57/rqw9CLGiccA/QvSG7NsHdHUjzHwUtDueQxeqIJlrscqxaN5ROZQKB5v
    xfCc9+uzjyDi5P0A37dwNuYTEbw/3iy1hKVeq7gblCZ36uBuQDR8wdtE6esS0M/O
    n7pJTG39SxLJF/gLrGIkjz7riMSlfPuHIUgl4lHeJs+JCGYabyvS7ZxwYhNZj+dp
    oT7gxdwRyfJ6d/rmqqnfpcxcgcdzoUt3yLeHkOha86u99RViQwnyt+Dercfl7qql
    dz+Zhvse5kQiUfgMjl6cOcStMZ51oEvfKEdgAfK6X27hVEU7QayNnQgVmjtx5Q5w
    jQRXpENefu4CB+LgeJ8CAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
    MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
    BBQ9u7bot+q63lVNPPbHekGehbR3pDANBgkqhkiG9w0BAQsFAAOCAQEArZQLOSEt
    /n7SGiAVRH/3jTTDGZ8XAd0PAOqfgLg16WShpAf0IhRDih53nPkeU5nx7+GG0l63
    7iZol6XRAvLG2L24HUMj2DIKSDWgFXgiGinCD7yYW7h4L30CHYMn5Rz5ZlwMejb3
    AAumSm25j8FOagXWPL+d+6SKzNRStyANqmfrLTRQlkCZzxObCardXNnx+EFOF3Re
    /Yn/RRR5YAcFgM4qo/fr4ihvw4pa4qaI3CpzTKEekdFeZysE1UJz9vcriUJinI3K
    XR1rmoEjfXTZ8AICbG4P/GXbaO6hCqG2qkVBSc1EySL/MvCDD6jJcoL4brE5Oxrb
    SxX4K57BIW2/vw==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/description: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-02-01T14:45:09Z"
  name: kube-root-ca.crt
  namespace: guestbook
