apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeU1ERXpNREV4TkRNME1Wb1hEVE15TURFeU9URXhORE0wTVZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT3c5CmpiaXQ0VDU3L3JxdzlDTEdpY2NBL1F2U0c3TnNIZEhVanpId1V0RHVlUXhlcUlKbHJzY3F4YU41Uk9aUUtCNXYKeGZDYzkrdXpqeURpNVAwQTM3ZHdOdVlURWJ3LzNpeTFoS1ZlcTdnYmxDWjM2dUJ1UURSOHdkdEU2ZXNTME0vTwpuN3BKVEczOVN4TEpGL2dMckdJa2p6N3JpTVNsZlB1SElVZ2w0bEhlSnMrSkNHWWFieXZTN1p4d1loTlpqK2RwCm9UN2d4ZHdSeWZKNmQvcm1xcW5mcGN4Y2djZHpvVXQzeUxlSGtPaGE4NnU5OVJWaVF3bnl0K0RlcmNmbDdxcWwKZHorWmh2c2U1a1FpVWZnTWpsNmNPY1N0TVo1MW9FdmZLRWRnQWZLNlgyN2hWRVU3UWF5Tm5RZ1ZtanR4NVE1dwpqUVJYcEVOZWZ1NENCK0xnZUo4Q0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJROXU3Ym90K3E2M2xWTlBQYkhla0dlaGJSM3BEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFyWlFMT1NFdAovbjdTR2lBVlJILzNqVFRER1o4WEFkMFBBT3FmZ0xnMTZXU2hwQWYwSWhSRGloNTNuUGtlVTVueDcrR0cwbDYzCjdpWm9sNlhSQXZMRzJMMjRIVU1qMkRJS1NEV2dGWGdpR2luQ0Q3eVlXN2g0TDMwQ0hZTW41Uno1Wmx3TWVqYjMKQUF1bVNtMjVqOEZPYWdYV1BMK2QrNlNLek5SU3R5QU5xbWZyTFRSUWxrQ1p6eE9iQ2FyZFhObngrRUZPRjNSZQovWW4vUlJSNVlBY0ZnTTRxby9mcjRpaHZ3NHBhNHFhSTNDcHpUS0Vla2RGZVp5c0UxVUp6OXZjcmlVSmluSTNLClhSMXJtb0VqZlhUWjhBSUNiRzRQL0dYYmFPNmhDcUcycWtWQlNjMUV5U0wvTXZDREQ2akpjb0w0YnJFNU94cmIKU3hYNEs1N0JJVzIvdnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: Z3Vlc3Rib29r
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklqVnNkMkpqVm05UFlWTjZYemhGYzJKTVgwTXhNV2d3V1dsbmVIUkJXVjlYZWpCVFRqRjFTMGRqWkdNaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpuZFdWemRHSnZiMnNpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxZM0psZEM1dVlXMWxJam9pWkdWbVlYVnNkQzEwYjJ0bGJpMW5OWG81Y2lJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKa1pXWmhkV3gwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pTldNeFlUSmxNV0l0TkRFd1pTMDBObUZoTFdGbE1HSXRaV1l6WVdFNVpUQTBNR016SWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tZDFaWE4wWW05dmF6cGtaV1poZFd4MEluMC5SRXFpNDVvRXpqQklJYlhyNG5UV05LYUJRMDRoSVdNZ2VWTzVWd000emdWRzlVaWZXLVBhTlpWSEdfV2JjZG9yMkhSYnRnb0xXbG9tUXFUcVY4NHZEQnQ2VUl6Rld0c24wRlp0QXJoVlVtQnlXMllOZDdSX2Z6SXlHYUYxdzBzaktvbGhUTWVDV2tiZ2puWVNmWENZQ0hnQTlMeHE0bnlJbHVlMF9NRF9GZ3lJYVBNX014UnBrRkNfS3M1ZmktQWNnNkV0cEtuYkc1QTc5dEN2eGhjaTBrSFdGVV9yNmRyZjQ5OUNoN2loQ3hEdmhFekM4RDcweHk2SFJ2WWhzY0pqZjctVk1zQWsyMW9URmJSc1dUTllrSUdXLTNqQTFBUFlNY0lic3M0bWphOFdHSUUtZzU5NjlrUllLNEplT0tmcldCalAzSUppN2FYY2xNOEY0dUdTQmc=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 5c1a2e1b-410e-46aa-ae0b-ef3aa9e040c3
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-02-01T14:45:09Z"
  name: default-token-g5z9r
  namespace: guestbook
type: kubernetes.io/service-account-token
